# folder = '../data'
folder = '../sample_data'
to_crs = {'init': 'epsg:32632'}
# graphmlName = '../data/odense_dk_2019_10000m_pedestrian_osm_20190902.graphml'
graphmlName = '../ample_graphml'
# graphmlProj_name = 'odense_dk_2019_10000m_pedestrian_osm_20190902_proj.graphml'
graphmlProj_name = 'sample_graphml_proj'

# geopackagePath = '../data/odense_dk_2019.gpkg'
geopackagePath = '../sample_data/sample_odense.gpkg'
samplePoints = 'urban_sample_points'
destinations = 'destinations'
hex250 = 'pop_ghs_2015'
nodes = 'nodes'
edges = 'edges'
# output_gpkgPath = '../data/global_indicators_city.gpkg'
output_gpkgPath = '../sample_data/global_indicators_city.gpkg'
